# Generated by Django 3.2.9 on 2022-02-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passengers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passengers',
            new_name='Passenger',
        ),
    ]
